version: '3.8'

services:
  db:
    image: postgres:17.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: music_library
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=123456
      - DB_NAME=music_library
      - API_BASE_URL=http://external-api:8080
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/app/migrations

  external-api:
    image: kennethreitz/httpbin # Простой мок-сервис для тестирования
    ports:
      - "8081:80" # Маппинг порта: 8081 на хосте -> 80 в контейнере

volumes:
  pgdata: